import {
  defaultConfig,
  type FlowNode,
  type Config,
  type Workflow,
  uid,
  clone,
} from "./model";
const node = (
  id: string,
  type: Config["type"],
  x: number,
  y: number,
  extra: object = {},
  label?: string,
): FlowNode => ({
  id,
  label:
    label ??
    (
      {
        input: "دادهٔ اولیه",
        http: "دریافت پست‌ها",
        filter: "پست‌های کاربر اول",
        sort: "جدیدترین‌ها",
        output: "جدول نتایج",
        condition: "کاربر فعال است؟",
        delay: "فرصت بازیابی",
      } as const
    )[type],
  position: { x, y },
  config: { ...defaultConfig(type), ...extra } as Config,
});
const base = (
  id: string,
  name: string,
  description: string,
  nodes: FlowNode[],
  edges: Workflow["edges"],
): Workflow => ({
  schemaVersion: 1,
  id,
  name,
  description,
  nodes,
  edges,
  createdAt: Date.now(),
  updatedAt: Date.now(),
});
const edge = (
  source: string,
  target: string,
  port: "out" | "true" | "false" = "out",
) => ({ id: source + "-" + target, source, target, port });
export const templates: Workflow[] = [
  base(
    "public",
    "از API تا جدول",
    "دریافت پست‌ها، فیلتر بر اساس userId و مرتب‌سازی؛ آمادهٔ خروجی CSV.",
    [
      node("i", "input", 40, 80),
      node("h", "http", 350, 80, { transport: "live" }),
      node("f", "filter", 660, 80),
      node("s", "sort", 660, 320),
      node("o", "output", 350, 320),
    ],
    [edge("i", "h"), edge("h", "f"), edge("f", "s"), edge("s", "o")],
  ),
  base(
    "conditional",
    "دو مسیر، یک تصمیم",
    "شرط را تغییر بده و ببین درخواست مسیر غیرفعال اصلاً اجرا نمی‌شود.",
    [
      node("i", "input", 30, 230, { value: { active: true } }),
      node("c", "condition", 340, 230, { path: "active", value: true }),
      node("h", "http", 660, 70, { transport: "fixture" }),
      node("d", "delay", 660, 390, { ms: 400 }),
      node("o", "output", 990, 70),
      node("n", "output", 990, 390),
    ],
    [
      edge("i", "c"),
      edge("c", "h", "true"),
      edge("c", "d", "false"),
      edge("h", "o"),
      edge("d", "n"),
    ],
  ),
  base(
    "recovery",
    "دادهٔ محلی، اجرای قابل ادامه",
    "بدون اینترنت اجرا کن. هنگام تأخیر صفحه را تازه کن و از نقطهٔ ثبت‌شده ادامه بده.",
    [
      node("i", "input", 40, 80),
      node("h", "http", 350, 80, { transport: "fixture" }),
      node("d", "delay", 660, 80, { ms: 12000 }),
      node("f", "filter", 660, 320),
      node("o", "output", 350, 320),
    ],
    [edge("i", "h"), edge("h", "d"), edge("d", "f"), edge("f", "o")],
  ),
  base(
    "multi-filter",
    "گزارش کاربر با پالایش چندمرحله‌ای",
    "شناسهٔ کاربر را به درخواست آزمایشی بفرست، نتایج را در دو مرحله پالایش و مرتب کن و جدول بساز.",
    [
      node("i", "input", 40, 180, { value: { userId: 2 } }, "کاربر موردنظر"),
      node(
        "h",
        "http",
        340,
        180,
        {
          transport: "fixture",
          mappings: [{ from: "userId", to: "userId", target: "query" }],
        },
        "پست‌های کاربر",
      ),
      node(
        "f1",
        "filter",
        640,
        180,
        { path: "id", operator: "gt", value: 12 },
        "شناسه‌های بزرگ‌تر از ۱۲",
      ),
      node(
        "f2",
        "filter",
        940,
        180,
        { path: "title", operator: "contains", value: "نتیجه" },
        "عنوان‌های دارای نتیجه",
      ),
      node(
        "s",
        "sort",
        1240,
        180,
        { path: "id", direction: "desc", mode: "number" },
        "جدیدترین پست‌ها",
      ),
      node("d", "delay", 1540, 180, { ms: 300 }, "مکث پیش از خروجی"),
      node(
        "o",
        "output",
        1840,
        180,
        { columns: ["id", "userId", "title"] },
        "جدول پست‌های منتخب",
      ),
    ],
    [
      edge("i", "h"),
      edge("h", "f1"),
      edge("f1", "f2"),
      edge("f2", "s"),
      edge("s", "d"),
      edge("d", "o"),
    ],
  ),
  base(
    "priority-routes",
    "دو مسیر پردازش بر اساس اولویت",
    "اولویت ورودی تعیین می‌کند کدام مسیر آزمایشی اجرا شود؛ هر مسیر پالایش و خروجی خودش را دارد.",
    [
      node(
        "i",
        "input",
        40,
        260,
        { value: { priority: "high", userId: 3 } },
        "درخواست با اولویت",
      ),
      node(
        "c",
        "condition",
        340,
        260,
        { path: "priority", value: "high" },
        "اولویت بالا است؟",
      ),
      node(
        "h1",
        "http",
        640,
        60,
        {
          transport: "fixture",
          mappings: [{ from: "userId", to: "userId", target: "query" }],
        },
        "دریافت مسیر فوری",
      ),
      node(
        "f1",
        "filter",
        940,
        60,
        { path: "id", operator: "gt", value: 20 },
        "پست‌های تازه‌تر",
      ),
      node(
        "s1",
        "sort",
        1240,
        60,
        { path: "id", direction: "desc", mode: "number" },
        "ترتیب فوری",
      ),
      node(
        "o1",
        "output",
        1540,
        60,
        { columns: ["id", "title"] },
        "گزارش فوری",
      ),
      node("d", "delay", 640, 460, { ms: 250 }, "مکث مسیر عادی"),
      node(
        "h2",
        "http",
        940,
        460,
        {
          transport: "fixture",
          mappings: [{ from: "userId", to: "userId", target: "query" }],
        },
        "دریافت مسیر عادی",
      ),
      node(
        "f2",
        "filter",
        1240,
        460,
        { path: "id", operator: "lt", value: 30 },
        "پست‌های پیش از ۳۰",
      ),
      node(
        "o2",
        "output",
        1540,
        460,
        { columns: ["id", "title"] },
        "گزارش عادی",
      ),
    ],
    [
      edge("i", "c"),
      edge("c", "h1", "true"),
      edge("h1", "f1"),
      edge("f1", "s1"),
      edge("s1", "o1"),
      edge("c", "d", "false"),
      edge("d", "h2"),
      edge("h2", "f2"),
      edge("f2", "o2"),
    ],
  ),
  base(
    "nested-decisions",
    "درخت تصمیم با سه خروجی",
    "فعال‌بودن و نیاز به بررسی را در دو شرط پیاپی بسنج؛ هر شاخه فقط خروجی مربوط به خود را می‌سازد.",
    [
      node(
        "i",
        "input",
        40,
        320,
        { value: { active: true, audit: false, userId: 1 } },
        "وضعیت درخواست",
      ),
      node(
        "c1",
        "condition",
        340,
        320,
        { path: "active", value: true },
        "درخواست فعال است؟",
      ),
      node(
        "c2",
        "condition",
        640,
        170,
        { path: "audit", value: true },
        "بررسی ویژه لازم است؟",
      ),
      node(
        "h1",
        "http",
        940,
        20,
        {
          transport: "fixture",
          mappings: [{ from: "userId", to: "userId", target: "query" }],
        },
        "دریافت برای بررسی",
      ),
      node(
        "f",
        "filter",
        1240,
        20,
        { path: "id", operator: "lt", value: 5 },
        "پست‌های آغازین",
      ),
      node(
        "o1",
        "output",
        1540,
        20,
        { columns: ["id", "title"] },
        "گزارش بررسی",
      ),
      node(
        "h2",
        "http",
        940,
        320,
        {
          transport: "fixture",
          mappings: [{ from: "userId", to: "userId", target: "query" }],
        },
        "دریافت عادی",
      ),
      node(
        "s",
        "sort",
        1240,
        320,
        { path: "id", direction: "desc", mode: "number" },
        "مرتب‌سازی عادی",
      ),
      node(
        "o2",
        "output",
        1540,
        320,
        { columns: ["id", "title"] },
        "گزارش عادی",
      ),
      node("d", "delay", 640, 590, { ms: 200 }, "مکث مسیر غیرفعال"),
      node("o3", "output", 940, 590, { view: "json" }, "نتیجهٔ غیرفعال"),
    ],
    [
      edge("i", "c1"),
      edge("c1", "c2", "true"),
      edge("c2", "h1", "true"),
      edge("h1", "f"),
      edge("f", "o1"),
      edge("c2", "h2", "false"),
      edge("h2", "s"),
      edge("s", "o2"),
      edge("c1", "d", "false"),
      edge("d", "o3"),
    ],
  ),
];
export function fromTemplate(template: Workflow): Workflow {
  const w = clone(template);
  w.id = uid();
  w.createdAt = w.updatedAt = Date.now();
  return w;
}
export function emptyWorkflow(): Workflow {
  return base(uid(), "گردش‌کار تازه", "", [node(uid(), "input", 100, 160)], []);
}
